### ISSUE TITLE
As a user, I want an introductory text, so I can better visualize the environment

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#13]

**Comment by vjpixel** [comment]
- [ ] 01
- [ ] 01

**Comment by vjpixel** [comment]
Information that we need to give:
- When we publish a new image, we'll send an email to all users
- Please open in the computer
- Please give feedback (include instructions)

**Comment by vjpixel** [comment]
This is the feedback form, so we need to include specific instructions.

![Screenshot from 2020-04-07 12-38-34](https://user-images.githubusercontent.com/1034796/78689601-e5a9e680-78cc-11ea-8f23-38e3e0e5fffa.png)

**Comment by vjpixel** [comment]
Right now we need to write an onboarding email, the first email every user will receive from us.

**Comment by vjpixel** [comment]
The first version that was written:

> Oi XYZ,

fico feliz de ter você nessa jornada!

bucoli.co surgiu de minha necessidade, como morador de uma metrópole, de "fugir" da cidade para relaxar. Nós, que passamos em média 7 horas por dia olhando para telas, esquecemos de olhar à nossa volta, esquecemos que o tédio é uma maneira de sentir prazer.

Eu montei a primeira versão dele em 2017, mas nunca lancei por medo de gritar no vácuo... receio das pessoas não verem "utilidade" nele. Por trás disso, havia o medo de nossa sociedade consumista, que vê tudo como produto ou serviço, não entender que o bucoli.co é uma oportunidade de ter uma janela.

O medo não sumiu, mas a vontade de compartilhar essa janela com as pessoas agora é mais forte que ele. A maior parte disso é culpa de Tiago Bugarin, amigo de longa data. Quando eu falei de minha vontade de retomar o projeto a resposta dele foi "bó brincar :)". Ele, como programador, é o responsável pela construção da janela.

Como tester, peço que você acesse o website e me diga o que acha e, o mais importante, como acha que poderíamos contruir uma janela que te ajude a enxergar algo além das paredes à sua volta.

Acesse bucoli.co e me escreva de volta.

Grato!

**Comment by vjpixel** [comment]
Version proposed by Joshu:

> Oi Joshu,
fico feliz de ter você nessa jornada!
 
bucoli.co é uma janela para ... 
... relaxar.
... pensar na vida.
... se reencontrar.

Nós, que passamos em média 7 horas por dia olhando para telas, esquecemos de olhar à nossa volta, esquecemos que o tédio é uma maneira de sentir prazer.
 
Eu montei a primeira versão dele em 2017, mas nunca lancei pois o momento não era adequado ... Eu tinha receio de não verem "utilidade" neste projeto. Além disso, havia o medo de nossa sociedade consumista, que vê tudo como produto ou serviço, não entender que o bucoli.co é uma oportunidade de ter uma janela.
 
O tempo mudou, o mundo mudou.

Como tester, peço que você acesse o website e me diga o que acha e, o mais importante, como acha que poderíamos construir uma janela que te ajude a enxergar algo além das paredes à sua volta.
 
Acesse bucoli.co e me escreva de volta.
 
Grato!

**Comment by bruquevedo** [comment]
Oi Joshu,

fico feliz de ter você nessa jornada!

bucoli.co é uma janela para ...
... relaxar.
... pensar na vida.
... se reencontrar.

Nós, que passamos em média 7 horas por dia olhando para telas, esquecemos de olhar à nossa volta, esquecemos que o tédio é uma maneira de sentir prazer.

Eu montei a primeira versão dele em 2017, mas nunca lancei pois o momento não era adequado ... Eu tinha receio de não verem "utilidade" neste projeto. Além disso, havia o medo de nossa sociedade consumista, que vê tudo como produto ou serviço, não entender que o bucoli.co é uma oportunidade de ter uma janela.

O tempo mudou, o mundo mudou.

Como tester, peço que você acesse o website e desfrute desse momento de contemplação. Depois, acesse o link de feedback dentro do site e responda as perguntas que deixamos lá para você. 
Nos ajude a construir uma janela que te ajude a enxergar algo além das paredes à sua volta.

Acesse bucoli.co e me escreva de volta.

Você receberá um próximo e-mail na semana que vem.

Grato!

**Comment by bruquevedo** [comment]
Sugestões de título:

Pare por um momento e contemple o que temos para te mostrar;

Abra este e-mail e relaxe por um instante;

Abra este e-mail e contemple o que temos para te mostrar;

O bucoli.co vai te ajudar a relaxar por um momento

**Comment by bruquevedo** [comment]
Oi Bruna Quevedo,

fico feliz de ter você nessa jornada!

bucoli.co é uma janela para...
 ...relaxar.
  ...pensar na vida.
   ...se reencontrar.

Nós, que passamos muitas horas por dia olhando para telas, esquecemos de olhar à nossa volta, esquecemos que a contemplação é uma maneira de sentir prazer.

Você faz parte de um pequeno grupo de amigos que convidamos porque valorizamos a opinião e acreditamos ter interesse no projeto. Nos ajude a construir uma janela que te permita enxergar algo além das paredes à sua volta.

Acesse o bucoli.co e desfrute de um momento de contemplação. Depois, volte aqui neste e-mail e me diga: como você acha que poderíamos construir uma janela que te ajude a enxergar algo além das paredes à sua volta?

Grato!

P.S.: Respire fundo, o bucoli.co está em desenvolvimento. Você receberá um próximo e-mail na semana que vem.
