### ISSUE TITLE
As a user, I want to have a menu button, so I can better view the picture.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#14]
_Deadline: Fri 18:00_

We agreed that's the best way to have a clear view of the picture is by having a discreet menu button. When the user clicks it, it opens the options.

We need to implement a menu.

**Comment by vjpixel** [comment]
I just updated this issue's desciption.

**Comment by vjpixel** [comment]
Since we're already discussing things that we want the users to have easy access, I propose we add a menu button, like the one in the picture.

![Screenshot from 2020-04-06 10-30-24](https://user-images.githubusercontent.com/1034796/78570494-71534280-77fb-11ea-8c75-c3101cee06d0.png)

**Comment by tiagobugarin** [comment]
the first implementation of the menu and its behavior is done. check it out at `alpha.bucoli.co`!!
i think there is room for improvements and will give some more attention in the next sprint.

**Comment by vjpixel** [comment]
People can't do feedback from the About page.

I propose we put the menu there (changing the link from Sobre to Home). This way, we can also get rid of the back button from the text.

**Comment by tiagobugarin** [comment]
hmmmm nice idea!

**Comment by tiagobugarin** [comment]
@vjpixel, suggestion implemented. get a look at `alpha.bucoli.co/about.htm`

**Comment by vjpixel** [comment]
Great!
