### ISSUE TITLE
As a staff member, I want to have a email marketing tool, so I can automatize sending emails

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#16]
The requisites are:
- Free plan
- A/B testing features
- Easy to use

**Comment by vjpixel** [comment]
@tiagobugarin Can you please review?

If you received the test email, I would consider this task done.

**Comment by tiagobugarin** [comment]
no email received

**Comment by vjpixel** [comment]
Are you sure? On SendPulse system, it says:

![Screenshot from 2020-04-07 15-22-05](https://user-images.githubusercontent.com/1034796/78705292-a76bf180-78e3-11ea-85fe-453dfd85be1a.png)
