### ISSUE TITLE
As a staff member, I want to have a new first image, so I can give a better experience to the testers

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#20]

**Comment by vjpixel** [comment]
Feedback from users:

> Acho que as imagens poderiam ser trocadas diariamente. E as antigas a
poderiam ficar num cantinho para quem quiser revisitar.

> (...) entendi que as imgs iam mudar cada vez que eu entrasse, mas continua mesma. 

> Uma sugestão: q a foto seja trocada a duas ou três vezes ao dia, proporcionando o dia todo novas experiências e contemplação para o público

**Comment by bruquevedo** [comment]
Delete the image BUCOLICO_01 from the images to be displayed on the site;
![BUCOLICO_01](https://user-images.githubusercontent.com/63117285/78931113-c1403c80-7a7b-11ea-90a5-398032fb47c6.jpg)

**Comment by bruquevedo** [comment]
@tiagobugarin use the image BUCOLICO_01_V1 (uplodead on the google drive bucolico folder)
![BUCOLICO_01_V1](https://user-images.githubusercontent.com/63117285/78932557-1e3cf200-7a7e-11ea-9550-04498803594c.jpg)

**Comment by bruquevedo** [comment]
https://drive.google.com/open?id=1k_i898JfSPFtOepmbkEOUAqZ_Usr-lel

**Comment by JoshuSantos** [comment]
What if we ACCUMULATE the images, so in the future, the FIRST image of the DAY is ALWAYS a NEW one... BUT if the user returns more times on the SAME day, the other images will appear RANDOMLY?

**Comment by JoshuSantos** [comment]
What if we had a "REFRESH button" in order to randomize  the images as the user wants?

**Comment by bruquevedo** [comment]
@JoshuSantos we suggest you to open a new issue about the images frequency
