### ISSUE TITLE
As a staff member, I want to know who users prefer to be the email sender, so I can increase the impact of the messages

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#24]
There's a hypothesis that people's connection to the project will be increased if the sender of the emails is the brand itself.

Our first A/B test in the emails will be changing the sender. We still have a small userbase, so we need to be careful when analysing the results.

As soon as we have results, I'll publish them here.

**Comment by vjpixel** [comment]
The way SendPulse divided the emails doesn't allow us to get to a conclusion.

**Comment by vjpixel** [comment]
As I addressed on #52, we need to create a specific email account for bucoli.co.

And we just agreed that Bruna will be responsible for email feedback (#40 ).

This makes me wonder: what if Bruna signs the next email?

**Comment by vjpixel** [comment]
@bruquevedo @tiagobugarin @JoshuSantos 

What do you think?

**Comment by bruquevedo** [comment]
@vjpixel I think we can try

**Comment by tiagobugarin** [comment]
I think it is an excellent idea.
