### ISSUE TITLE
As a PM, I want feedback from the email, so I can send a better email to the users.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#25]
Send the alpha version of the email to the staff members so they can give feedback to improve it.

Ask them to:
- [ ] Check the grammar
- [ ] Review the design
- [ ] Propose other improvements

**Comment by JoshuSantos** [comment]
Oi xxxxxxxxxxxxxxxxxxxxx,

fico feliz de ter você nessa jornada!
 
bucoli.co é uma janela para ... 
... relaxar.
... pensar na vida.
... se reencontrar.

Criei o bucoli.co porque percebi quanto tempo eu passava imerso no computador. Eu, assim como você, fico em média 7 horas por dia olhando para telas.

Se você também nunca notou que ficava tanto tempo online, seja bem-vindo ao clube. Mas sabe quem percebe isso? A nossa mente. O nosso cérebro.

É tanto virtual que esquecemos de olhar à nossa volta. 
Esquecemos que o diferente, o vazio, os pensamentos perdidos... são maneiras de sentir prazer.
 
Com o bucoli.co, eu proponho que tenhamos, em meio a esse universo digital, uma janela. Onde nossos pensamentos possam se perder, pra que a gente, então, consiga se reencontrar.

Topa?

Como tester, peço que você acesse o website e me diga o que acha. Ah, e o mais importante: como você acha que poderíamos construir uma janela que te ajude a enxergar algo além das paredes à sua volta.
 
Acesse bucoli.co e me escreva de volta.
 
Obrigado!

**Comment by vjpixel** [comment]
Can you please review @tiagobugarin ?

**Comment by vjpixel** [comment]
@JoshuSantos Can you please confirm that the email was sent?
