### ISSUE TITLE
As a staff member, I want organized feedback, so I can reach and analyse it easily

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#29]
The feedback is only published in the Slack channel "feedback", making it hard to associate it with the questions and to make notes.

My proposed solution is to create a spreadsheet with the feedback with:
* Questions
* Answers
* Improvements proposed
* Main discoveries

**Comment by vjpixel** [comment]
I created the spreadsheet and shared in Slack. Please confirm @bruquevedo

**Comment by bruquevedo** [comment]
ok, received.
