### ISSUE TITLE
As a staff member, I want organized tasks, so I can better collaborate

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#31]
The team is still starting to work together and we're still adjusting our way to communicate. As a goal-driven team, our main tool of communication should be GitHub. One way to engage the team with the tool is having well described and organized tasks.

We need to have the sprint tasks created and organized on GitHub.

_Deadline: Wed 14:00_

**Comment by vjpixel** [comment]
@tiagobugarin Can you please review?

**Comment by tiagobugarin** [comment]
It is done! A-OK!

**Comment by vjpixel** [comment]
@tiagobugarin You forgot to close the issue, can you do that?
