### ISSUE TITLE
As a user, I want a beautiful e-mail, so I feel pleasured with bucoli.co

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#34]
We hadn't time to plan the design of the template of the first email.

We want to improve the design of the email.

_Deadline: Wed 21:00_

**Comment by vjpixel** [comment]
@JoshuSantos can you edit the template on SendPulse?

**Comment by JoshuSantos** [comment]
REGULAR text: normal, 70% black, #4d4d4d
QUESTION text: bold, 70% black, #4d4d4d
P.S. text: italic, 70% black, #4d4d4d
LINK text: bold, 70% cyan, 20% black, #00a1cb

**Comment by JoshuSantos** [comment]
@bruquevedo and @vjpixel , review the SECOND email.

**Comment by bruquevedo** [comment]
@JoshuSantos for me it's ok :)
