### ISSUE TITLE
As a user, I want an onboarding, so I can experience the context of the photo

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#35]
_Deadline: Wed 21:00_

The team believes that delivering a photo isn't enough for people to understand the bucoli.co's proposal.

We want to write an email related to the picture, so the people can feel immersed in the picture's context.

**Comment by JoshuSantos** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

E se, em vez de focar no que falta, você pensasse em como é bom estar presente, vivendo essa pausa?

Relaxe conosco. Clique aqui e curta a foto da semana.

E não se esqueça: responda este e-mail contando o que achou da experiência e como podemos melhorá-la.

Obrigado!

P.S.: Respire fundo, o bucoli.co está em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by JoshuSantos** [comment]
@vjpixel and @bruquevedo , please, review this.

**Comment by bruquevedo** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

E se, em vez de focar no que falta, você pensasse em como é bom estar presente, vivendo essa pausa?

Relaxe conosco. Acesse bucoli.co e curta a foto da semana.

E não se esqueça: responda este e-mail contando o que achou da experiência e como podemos melhorá-la.

Obrigado!

P.S.: Respire fundo, o bucoli.co está em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by bruquevedo** [comment]
> 
> 
> Relaxe conosco. Clique aqui e curta a foto da semana.
> 
>

@JoshuSantos For now, I just changed the call to action. We need to wait for @vjpixel to tell us what is going to be feedback answer to finish the text

**Comment by JoshuSantos** [comment]
@bruquevedo , please check the PDF and comment.
@tiagobugarin , please consider those colors and fonts for the email setup.

REGULAR text: Source Sans Pro Semi-bold 600, 70% black.
QUESTION text: Source Sans Pro Black 900, 70% black.
P.S. text: Source Sans Pro Semi-bold 600 italic, 70% black.
LINK text: Source Sans Pro Black 900, 70% cyan, 20% black.


[
[bucolico_email.pdf](https://github.com/memeLab/bucoli.co/files/4489924/bucolico_email.pdf)
](url)

**Comment by JoshuSantos** [comment]
@bruquevedo please check the PDF and comment.
@tiagobugarin please consider those colors and fonts for the email setup.

REGULAR text: normal, 70% black, #4d4d4d
QUESTION text: bold, 70% black, #4d4d4d
P.S. text: italic, 70% black, #4d4d4d
LINK text: bold, 70% cyan, 20% black, #00a1cb

**Comment by JoshuSantos** [comment]
All the comments, from the TEXT of the email that I put before up to here, is related to issue #34 .

**Comment by vjpixel** [comment]
@JoshuSantos the responsibility of formatting the email is not @tiagobugarin's, he only has access to the website.

Also, we have a specific task for the formatting: #34, can you please publish there?

**Comment by vjpixel** [comment]
Oh, I wrote my comment and only see yours after hit send. @JoshuSantos  =)

**Comment by bruquevedo** [comment]
@JoshuSantos and about the fonts infos for the site, I belive that the correct issue is the #43

**Comment by JoshuSantos** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

E se, em vez de focar no que falta, você pensasse em como é bom estar presente, vivendo essa pausa?

Relaxe conosco. Acesse bucoli.co e curta a foto da semana.

E lembre-se: responda este e-mail contando o que achou da experiência e onde ele estava: caixa de entrada, spam ou outro local?

Obrigado!

P.S.: Respire fundo, o bucoli.co está em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by bruquevedo** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

E se, em vez de focar no que falta, você pensasse em como é bom estar presente, vivendo essa pausa?

Relaxe conosco. Acesse bucoli.co e aprecie a vista da semana.

E lembre-se: responda este e-mail contando o que achou da experiência e onde ele estava: caixa de entrada, spam ou outro local?

Obrigado!

P.S.: Respire fundo, o bucoli.co está em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by bruquevedo** [comment]
@vjpixel could you please review the text?

**Comment by vjpixel** [comment]
One user proposed that to just have one link to "bucoli.co" on the email text. I think we should try that.

**Comment by bruquevedo** [comment]
Sugestão 1: E lembre-se: responda este e-mail contando se ele estava na caixa de entrada, spam ou outro local? Tivemos questões técnicas na nossa última mensagem contigo e sua resposta é muito importrante para nós.

Sugestão 2: Tivemos questões técnicas com o recebimento do nosso último e-mail, por isso, pedimos para você nos responder onde você recebeu o e-mail dessa semana: na caixa de entrada, spam ou outro local? Sua resposta é muito importante para nós.

**Comment by JoshuSantos** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

E se, em vez de focar no que falta, você pensasse em como é bom estar presente, vivendo essa pausa?

Relaxe conosco. Acesse bucoli.co e aprecie a vista da semana.

Tivemos questões técnicas com o recebimento do nosso último e-mail, por isso, pedimos para você nos responder onde você recebeu o e-mail dessa semana: na caixa de entrada, spam ou outro local? Sua resposta é muito importante para nós.

Obrigado!

P.S.: Respire fundo, estamos em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by JoshuSantos** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

E se, em vez de focar no que falta, você pensasse em como é bom estar presente, vivendo essa pausa?

Relaxe conosco. Acesse bucoli.co e aprecie a vista da semana.

Tivemos questões técnicas com o recebimento do nosso último e-mail, por isso nos diga onde você recebeu o e-mail dessa semana: na caixa de entrada, spam ou outro local? Sua resposta é muito importante para nós.

Obrigado!

P.S.: Respire fundo, estamos em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by JoshuSantos** [comment]
Você já fez as contas?

Talvez, você esteja pensando na viagem que não fez.
Nos amigos que não encontrou.
Nos momentos que foram adiados por conta da pandemia.

É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.

**E se, em vez de focar no que falta, você se permitisse pensar em como é bom estar presente, vivendo essa pausa?**

Relaxe conosco. Acesse bucoli.co e aprecie a vista da semana.

Tivemos questões técnicas com o recebimento do nosso último e-mail, por isso nos diga onde você recebeu o e-mail dessa semana: na caixa de entrada, spam ou outro local? Sua resposta é muito importante para nós.

Obrigado!

_P.S.: Respire fundo, estamos em desenvolvimento. Você receberá um próximo e-mail na semana que vem._

**Comment by bruquevedo** [comment]
@vjpixel could you please review the issue?

**Comment by vjpixel** [comment]
> Você já fez as contas?
> 
> Talvez, você esteja pensando na viagem que não fez.
> Nos amigos que não encontrou.
> Nos momentos que foram adiados por conta da pandemia.
> 
> É bem verdade que a vida está no "pause" para muita gente. Mas, às vezes, pausas são necessárias para a gente se reencontrar.
> 
> E se, em vez de focar no que falta, você se permitisse pensar em como é bom estar presente, vivendo essa pausa?
> 
> Relaxe conosco. Acesse bucoli.co e aprecie a vista da semana.

Tivemos questões técnicas com o recebimento do nosso último e-mail, por isso nos diga onde você recebeu este o e-mail : na caixa de entrada, spam ou outro local? Sua resposta é muito importante para nós.

> Obrigado!


_P.S.: Respire fundo, você receberá o próximo e-mail na semana que vem._

**Comment by vjpixel** [comment]
We discussed on #24 and we decided to have Bruna as the sender of the email (using bucoli.co email address).

**Comment by vjpixel** [comment]
I have a new proposal for the email, based on the original text Vanessa created for the picture and on the question I proposed on #53 (please discuss the question in the original issue).

What do you think @bruquevedo @JoshuSantos @tiagobugarin ?

++

_É alto de onde você olha. 
A liberdade te empodera. 
A vista te encanta.
Quão sólida é a mata, 
composta por tantas árvores?
Tão sólida quanto as nuvens, 
mais densas que diáfanas.
Contemple o horizonte.
Encare a linha da montanha.
Para onde você seguiria?
Na paisagem, encontre-se._

++

Acesse bucoli.co e aprecie a vista da semana.

Considere que você precisa abrir nossa janela em um computador e que é melhor receber o email em um momento que possa apreciar a vista. Que dia e hora você prefere receber nossos emails semanais?

Obrigado!

P.S.: Respire fundo, estamos em desenvolvimento. Você receberá um próximo e-mail na semana que vem.

**Comment by bruquevedo** [comment]
@vjpixel @JoshuSantos and @tiagobugarin In my opinion, this is the path to the texts on bucoli.co. It delivers an experience, as well as the image. It brings curiosity about what the image will be and this can help to increase the number of visits to the site. This type of text converges with the idea of ​​creating a community for bucolico, where people will feel welcomed and remain for the positive feeling they have when receiving an email from bucolico.

**Comment by bruquevedo** [comment]
@vjpixel @JoshuSantos @tiagobugarin I'm responsible to give the testers a feedback, as you can see in the issue #40 . Because of it, we discussed in the issue #24 about testing send the next bucoli.co e-mail with my sign in the end. But, with this new proposal for the text of the next e-mail that @vjpixel brought to us I think that bucoli.co should sign the e-mail. And in my opinion there's no problem about the testers feedback be signed by me, because they know that we have a team working in the project. What do you think?

**Comment by vjpixel** [comment]
ok

**Comment by tiagobugarin** [comment]
I only now read the newest text proposal while listening to Pink Floyd's Us and Them and switching back and forth from the text to the `bucoli.co` site and it was amazing!!!!!

> is this real life?

**Comment by dotcontentstudio** [comment]
Pixel, I think this final proposal is great!
