### ISSUE TITLE
As a user, I want to get curious about the picture, so I get motivated to see it

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#36]
_Deadline: Wed 21:00_

The team believes that having the new picture on the email will make users engaged in visiting bucoli.co.

For this task to be completed #42 needs to be done.

We want to have a personalized logo with the new picture.

**Comment by bruquevedo** [comment]
this is the custom logo for the image of the week
![TOPO-BUCOLICO-02](https://user-images.githubusercontent.com/63117285/79493024-42a54b00-7ff7-11ea-9cab-8a7db3c5c6ac.jpg)

**Comment by JoshuSantos** [comment]
I agree.
