### ISSUE TITLE
As a staff member, I want to be sure that the email is ready, so I know we can send the final version

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#37]
_Deadline: Thu 14:00_

We had problems with previous emails not being as we wanted for different reasons.
For this task to be completed #35 and #36 need to be done.

We need to send a test email to the team so everyone can review it before we send the final version.

**Comment by bruquevedo** [comment]
Please put your feedback here @JoshuSantos @bruquevedo @tiagobugarin

**Comment by vjpixel** [comment]
We agreed @bruquevedo will be responsible for this task. I'll teach her how to do it.

**Comment by vjpixel** [comment]
test

**Comment by bruquevedo** [comment]
@vjpixel, @JoshuSantos and @tiagobugarin I sent the e-mail, please check and answer it

**Comment by tiagobugarin** [comment]
On it.

**Comment by bruquevedo** [comment]
@JoshuSantos e @vjpixel @tiagobugarin and I worked in some improvements to the e-mail and sent it again to all our staff. Please check and answer where did you find the e-mail and if the link is working

**Comment by vjpixel** [comment]
The email is in my inbox!

Qhen I click the bucoli.co link, I get this message:

![Screenshot from 2020-04-18 12-11-38](https://user-images.githubusercontent.com/1034796/79641442-faf4ff80-816d-11ea-934c-1a26bcad1ba7.png)

**Comment by JoshuSantos** [comment]
@bruquevedo , I received the email in my Inbox and the link worked just fine. 👍

**Comment by tiagobugarin** [comment]
email in the inbox and link was fine.
no idea why @vjpixel got that message. will have a look soon.

but heeeey, we have a different problem! this is good in my book. we moved  forward!!

**Comment by tiagobugarin** [comment]
This post suggests it may be the image.

https://dev.to/karllhughes/debugging-gmail-s-suspicious-link-warnings-45ia

**Comment by bruquevedo** [comment]
I received the e-mail in the inbox and the link is working perfectly. 
As @tiagobugarin said we moved forward and that's good! New problems, new challenges

**Comment by bruquevedo** [comment]
> 
> 
> This post suggests it may be the image.
> 
> https://dev.to/karllhughes/debugging-gmail-s-suspicious-link-warnings-45ia

ok, so I think we can take the image link off. What do you think?

**Comment by tiagobugarin** [comment]
@vjpixel i will send you only a test version just without the image link. so you can test.

**Comment by vjpixel** [comment]
Now warnings! Go, tiger!

**Comment by bruquevedo** [comment]
To understand how we avoid the spam box this time you can check the issue #32

**Comment by bruquevedo** [comment]
@tiagobugarin could you please close this issue?
