### ISSUE TITLE
As a user, I want to know that I can see a new photo, so I can have a new experience in the website

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#38]
The great moment! Tell the users that we have a new image.

To this task to be completed, #37 need to have the team feedback and suggested changes need to be addressed.

We need to send the final email to the users.

_Deadline: Fri 9:00_

**Comment by vjpixel** [comment]
Since @bruquevedo sent the final email, I'm transferring this task to her.

**Comment by bruquevedo** [comment]
@tiagobugarin can you review and close the issue please?
