### ISSUE TITLE
As a staff member, I want to be sure which users received the email, so I can send to the ones that didn't receive

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#39]
For the first email, we sent, only 28% of the users received it. 64% of the emails either went to the spam box or wasn't delivered.

We need to check with the users that didn't open it if they received it.

_Deadline: Mon 11:00 ?_

**Comment by vjpixel** [comment]
Did we define the new deadline for this task?

**Comment by bruquevedo** [comment]
hey @JoshuSantos @vjpixel once we have the information about the second e-mail sent to our testers I suggest three questions to be made:

1. If the e-mail wasn't opened: Did you received it? 
2. If the e-mail was opened but the person didn't access the link: Why didn't you access the link to visit bucoli.co?
3. If the person accessed the link but didn't give feedback: Why didn't you answer the question we asked in the e-mail?

**Comment by vjpixel** [comment]
Ok. I'm waiting for @JoshuSantos to tell me who I need to contact and I'll ask these questions.

**Comment by JoshuSantos** [comment]
Hello people.
I organized the MailChimp entries and out of 25 people, only 2 did not open the email.

@vjpixel please check with isabelj@gmail.com why she did not open it.
@vanessa please check with rodrigoalmeida021@gmail.com why he did not open it.

You can follow those questions:

1. If the e-mail wasn't opened: Did you received it?
2. If the e-mail was opened but the person didn't access the link: Why didn't you access the link to visit bucoli.co?
3. If the person accessed the link but didn't give feedback: Why didn't you answer the question we asked in the e-mail?

@bruquevedo on the MailChimp site I can see who opened (and clicked) on the email, but I do not see who answered the questions. Do you need us to check it with our contacts?

Thanks.

**Comment by vjpixel** [comment]
Hey @JoshuSantos,

You just told to whom we need to ask question 1. To whom we need to ask questions 2 and 3?

Also, I propose we ask a new question for everyone that opened: Did you open in a mobile or desktop device?

Also, Vanessa is not on bucoli.co's Github yet. @vanessa is not a user, so she won't receive your message.

**Comment by vjpixel** [comment]
@JoshuSantos Also, you put personal user information in your comment. Since this space is open, we can't do that. I edited your comment to remove them.

**Comment by vjpixel** [comment]
@JoshuSantos do you need help on this task? When do you think we'll have this data?
