### ISSUE TITLE
Visual clues to identify between links

### ISSUE THREAD

**Issue by tiagobugarin** [memeLab/bucoli.co#4]
A maiúscula vai ajuda a diferenciar do texto anterior, mas acho que cabe um hífen antes para diferenciar ainda mais

**Comment by vjpixel** [comment]
We agreed that we should change the order to "Sobre   Foto: Xxx Zzz" to better differentiate between itens

**Comment by vjpixel** [comment]
Since we've decided to move to a menu, I think that making it vertical will solve this issue.

**Comment by tiagobugarin** [comment]
Outdated
