### ISSUE TITLE
As a staff member, I want to have feedback organised, so I can easily analyse it

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#41]
Having a document organizing all the feedback help the team to easily find and analyze the feedback.

Also, the document has insights from the feedbacks that help us to define what to do next. 

We need to organize the feedbacks in the document.

_Deadline: Tue 18:00_

**Comment by JoshuSantos** [comment]
@bruquevedo , you are organizing the feedbacks sent to bucolico@memelab.com.br, right?

How can I get the data regarding who answered the questions on the email and who didn't?

**Comment by bruquevedo** [comment]
hey @JoshuSantos I just put the word ANSWERED together with OPENED and CLICKED in the BUCOLICO MAIL/TEST spreadsheet

**Comment by bruquevedo** [comment]
@JoshuSantos but for example, the feedbacks you sent me didn't answer the specific question we asked in the e-mail sent on april 18th and they didn't answered the email so I do know if I fill their names with ANSWERED or not

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?
