### ISSUE TITLE
As a user, I want to have a new photo, so I feel engaged with bucoli.co

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#42]
The users say they want always changing pictures, but we know that today we can only deliver one new per week.

We need to choose a new picture.

_Deadline: Wed 21:00_

**Comment by bruquevedo** [comment]
I suggest this one to bem the next image. I already sent it to @tiagobugarin 
![BUCOLICO_06](https://user-images.githubusercontent.com/63117285/79492380-4f756f00-7ff6-11ea-8cc4-3b320a9cbd52.jpg)

**Comment by bruquevedo** [comment]
@JoshuSantos could you please review and close the issue?

**Comment by JoshuSantos** [comment]
I like this image. Congrats.

**Comment by vjpixel** [comment]
@bruquevedo please remember that the task needs to be approved before you send the image to the developer.

**Comment by bruquevedo** [comment]
@vjpixel ok
