### ISSUE TITLE
As a user, I want a beautiful website, so I feel pleasured with bucoli.co

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#43]
Since we're will keep including new features and it's an image-focused website, it's important to have it well designed and pleasant.

@JoshuSantos is in charge of creating the design and @tiagobugarin of implementing it.

We want to improve the design of the website based on the new features.

_Deadline: Thu 14:00_

**Comment by vjpixel** [comment]
Do you have any update about this?

@tiagobugarin @JoshuSantos

**Comment by JoshuSantos** [comment]
@tiagobugarin , @bruquevedo can you review (or comment) on those suggestions that I put here:

https://github.com/memeLab/bucoli.co/issues/27#issuecomment-611721270

**Comment by bruquevedo** [comment]
@JoshuSantos the day you sent that suggestions me and @tiagobugarin discussed almost all of then.
I'm going to talk about my points based in this conversation.

1- I think that we don't need the border but we need to find the correct size and color of the SOBRE button (or any other button). Based in two feedbacks users like to have the image in all the screen and one of then proposed a full screen button;

2 - answered above;

3 - I think that it's a good ideia. Give different weights to the text can make it more attractive to be read;

4 - @tiagobugarin already implemented a back button. We can discuss about if it's good enough or need to improve it;

**Comment by vjpixel** [comment]
We agreed to close this unfinished issue. We'll create a new one on the next sprint.
