### ISSUE TITLE
As a user, I want to come back to the homepage, so I'm not stuck in the About

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#44]
We had a back button in our roadmap and users asked for it, so we consider this a priority.

We need to implement the test button.

_Deadline: Thu 14:00_

**Comment by tiagobugarin** [comment]
Back button at the about page is done.
@bruquevedo , would you please review that it is working correctly?

**Comment by bruquevedo** [comment]
@tiagobugarin is it in the bucoli.co ou in the alpha.bucoli.co?

**Comment by tiagobugarin** [comment]
sorry, `alpha.bucoli.co` !!! :)

**Comment by bruquevedo** [comment]
@tiagobugarin checked! It's really good to have the button and it's working correctly
