### ISSUE TITLE
As a user, I want a flawless website, so I can enjoy a great experience

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#45]
Since we already have users accessing our website, it's important to have a developed version.

We agreed that the URL should be alpha.bucoli.co.

We need to deploy a development website.

_Deadline: Thu 14:00_

**Comment by tiagobugarin** [comment]
It is done!

@vjpixel would you please review that `alpha.bucoli.co` is working correctly?

**Comment by vjpixel** [comment]
Yes, I can ope alpha.bucoli.co.
