### ISSUE TITLE
As a user of IE 4, I want a flawless website, so I can enjoy a great experience

### ISSUE THREAD

**Issue by bruquevedo** [memeLab/bucoli.co#46]
Since we have users that use different web browsers, we want to have the website compatible with web browsers with more market share.

We need to update the website to be compatible with the browsers that have at least a 5% market share.

_Deadline: Thu 14:00_

**Comment by tiagobugarin** [comment]
IE4.... ohhh nooooooooooooo
/me fake-faints

seriously, thou, went on to some stats for browser usage on dasktop and laptop computers to find out which ones stays over the +5% margin.

StatCounter - worldwide - mar/2019 até mar/2020 [1]:
* Chrome - 68,11%
* Firefox - 9,25
* Safari - 8,93%

NetMarketShare - worldwide - apr/2019 até mar/2020 [2]:
* Chome - 67,72%
* Firefox - 8,49%
* Internet Explorer - 6,97%
* Edge - 6,20%

W3Counter - Worldwide - mar/2020 [3]:
* Chrome - 59,3%
* Safari - 12,3%
* Internet Explorer & Edge - 9,1%

I would say Google Chrome, Mozilla Firefox, Apple Safari and Microsoft Edge. are the ones we should focus and we should disconsider Internet Explorer as it's not being actively maintained and is in the processes of vanishing from the stats.

[1] https://gs.statcounter.com/browser-market-share/desktop/worldwide
[2] https://www.netmarketshare.com/browser-market-share.aspx
[3] https://www.w3counter.com/globalstats.php

**Comment by tiagobugarin** [comment]
After validating the code with the [W3C Validator](https://validator.w3.org/) and verifying the compatibility with [BrowseEmAll - Cross Browser Testing](https://www.browseemall.com/Compatibility/ValidateHTML) I understand the code has good compatibility with modern browsers.

**Comment by tiagobugarin** [comment]
To facilitate de review i will make a little tutorial on how to get the code from the site and apply it to validators and compatibility testers.

Remember:
1. At this point we have two pages to test: the main page and the about page. Remember to analyze both pages at both online testers.
2. The testing was made with the `alpha.bucoli.co` version of the site.

It will be made in 2 parts: getting the code and analyze.

To get the code for any page you can follow this simple steps:
1. load the site with any web browser;
2. click anywhere in the browser window with the right button of the mouse or touchpad (if you are left handed use the left button instead) and select the option to see the source code of the page (or something to that effect)
3. You will be presented with the code of the page. Select everything and copy.
Now you have the code! Next we will analyze it.

The analyzes where made in two different sites for different effects: the W3C Validator checks if the code is ok and within the specification the page is using; the BrowseEmAll verifies the compatibility with known browsers to point out if something will not work or work partially.

W3C Validator
1. open the [W3C Validator](https://validator.w3.org/) and select the third tab "Validate by Direct Input";
2. Click at the large box that just appeared and paste the code you copied just before, at the first part;
3.Click the check button just below the box, to the right.
That's it! The verification should get an OK status with no errors or warnings.

BrowseEmAll
1. Open [BrowseEmAll](https://www.browseemall.com/Compatibility/ValidateHTML), click the big orange button "Let's Find Out"  and then, click the large box that just appeared and paste de code you copied just before, athe the first part;
2. Click the big orange button below the big box that says "Analyze".
That's it! A few very old brosers will show some problems with some modern JavaScript or not supporting some elements like the `svg` HTML element.

**Comment by tiagobugarin** [comment]
@vjpixel , would you review it please?

**Comment by vjpixel** [comment]
This is a great tutorial!

I followed the steps and I confirm everything is working great!

W3C Validator gave some recommendations. Maybe you want to follow them.

Both websites accept URL inputs. Why do you prefer the Copy>Paste way to check the code?

**Comment by tiagobugarin** [comment]
> Both websites accept URL inputs. Why do you prefer the Copy>Paste way to check the code?

i don't know... habits, i guess... old ones dies hard! :)
