### ISSUE TITLE
As a staff member, I want to collaborate on the email management, so we have a more distributed workflow

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#52]
SendPulse only allows access from one user.

Also, most of the emails sent until now were sent from Pixel's account.

We need to create a bucolico email account so we can address both problems.

**Comment by vjpixel** [comment]
@bruquevedo can you please confirm that the email was created and that it can access SendPulse?

**Comment by bruquevedo** [comment]
@vjpixel checked. Everthing working correctly

**Comment by vjpixel** [comment]
@bruquevedo If so, can you please close the issue?
