### ISSUE TITLE
As a staff member, I want user feedback, so I can improve the product

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#53]
Every sprint we ask a question to the users to drive our product improvement. The questions can be some information we need or some hypothesis the team wants to test.

We need to define this week's question.

**Comment by vjpixel** [comment]
The team has a theory says that it's best to send emails on weekdays, so users open the e-mail.on computers.

The only feedback we have from users about when to send the email is on weekends.

I propose we ask the users the best day and time to receive the email.

**Comment by vjpixel** [comment]
Consider that you need to open our window on a computer and that it’s better to receive the email in a moment you can enjoy the view. What time and day do you prefer to receive our weekly emails?

Considere que você precisa abrir nossa janela em um computador e que é melhor receber o email em um momento que possa apreciar a vista. Que dia e hora você prefere receber nossos emails semanais?

What do you think, @tiagobugarin @bruquevedo @JoshuSantos ?

**Comment by bruquevedo** [comment]
@vjpixel I considerer that it's a good question to our testers because sending the e-mails in the better day and hour can improve the views and feedbacks

**Comment by tiagobugarin** [comment]
I liked the way you phrased the question without a bias toward any conclusion. I mean, without using words like "weekdays" or "weekends" or "morning" or "noon" you avoided inducing the response and let the readers mind to really think about what they want or how they prefer to be contacted by bucoli.co.
