### ISSUE TITLE
As a user, I want a way to propose ideas, so I can contribute to the project

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#54]
_Deadline: Fri 18:00_

Today, the way we listen to the users is by email answering. Having a system will automatize the process of collecting feedback. We already did tests before with UserSurvey, and it seems to fulfill our needs.

We will implement UserSurvey feedback this week.

**Comment by vjpixel** [comment]
I just updated the description of this issue.

**Comment by tiagobugarin** [comment]
this one is an easy one. the code is already there just waiting to be enabled back.

**Comment by tiagobugarin** [comment]
@vjpixel it is already at the alpha.bucoli.co. would you please review it?

**Comment by vjpixel** [comment]
I tested and it's working as supposed to do.
