### ISSUE TITLE
As a staff member, I want organized tasks on GitHub, so I can better collaborate

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#55]
_Deadline: Tue 18:00_

We're always adjusting our way to communicate. As a goal-driven team, our main tool of communication is GitHub. 

We need to have the sprint tasks created and organized on GitHub.

**Comment by vjpixel** [comment]
Please review @tiagobugarin

**Comment by tiagobugarin** [comment]
Looks ok!

Closing and moving.

**Comment by vjpixel** [comment]
I updated the planning document: https://docs.google.com/document/d/1BLhg8CrgLVYTBMjy91jsvy48tm7BpBFGRgGyMU---Gs/edit

**Comment by vjpixel** [comment]
Model for reminders:

/remind #bucolico "Tasks with deadlines today for @Tiago #73 #72, for @vjpixel #74 #75 #76, for @Bruna Quevedo #56 # 59 #57 #58" Thu 9:00

**Comment by vjpixel** [comment]
@tiagobugarin, I just added all tasks on GitHub, created daily reminders on Slack, and created meetings on Calendar. Can you please review?

**Comment by tiagobugarin** [comment]
i think i saw every task, meeting and reminders... looks ok to me!

closing and moving

**Comment by vjpixel** [comment]
I just updated the description.

**Comment by vjpixel** [comment]
@tiagobugarin can you please check if I accomplished this?

Since it's too many tasks, and some of them will be solved twice, I have a proposal in a way that it doesn't take too much time for you: check your tasks (as a sample).

Check if your issues are organized in order to reflect the task planning we made in the Sprint Planning.

**Comment by vjpixel** [comment]
This Sprint I split this issue in two because it's too long. Now the schedule organization is in #86.

**Comment by tiagobugarin** [comment]
it looks like everything is in place for my sampled subjects ( ehehehe )

closing and moving
