### ISSUE TITLE
As a user, I want to have a new photo, so I feel engaged with bucoli.co

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#56]
_0.0.5 Deadline: Wed 16:00_

_0.0.6 Deadline: Thu 18:00_

The users say they want always changing pictures, but we know that today we can only deliver one new per week.

We need to choose a new picture.

**Comment by bruquevedo** [comment]
My suggestion to the next image is this one:

![BUCOLICO_04](https://user-images.githubusercontent.com/63117285/80125909-b354e600-8568-11ea-945b-95c7d1e4c288.jpg)

what do you think @vjpixel @JoshuSantos and @tiagobugarin ?

**Comment by tiagobugarin** [comment]
liked it very much!

**Comment by vjpixel** [comment]
I prefer to have a landscape.

**Comment by bruquevedo** [comment]
@vjpixel @tiagobugarin what about this one?

![0002](https://user-images.githubusercontent.com/63117285/80142788-2159d700-8582-11ea-8914-16913f50f583.jpg)

**Comment by JoshuSantos** [comment]
> I prefer to have a landscape.

I understand the theme of bucolico's site as landscape (mostly), @vjpixel ... on the other hand, I think it creates a nice change of rhythm. 

As a side note, @bruquevedo , maybe because of my previous trip to Capão, the closeup photo brought me back the memory of the coldness of the water. It wasn't something that I was expecting. I just felt. Funny, isn't it?

**Comment by JoshuSantos** [comment]
> @vjpixel @tiagobugarin what about this one?
> 
> ![0002](https://user-images.githubusercontent.com/63117285/80142788-2159d700-8582-11ea-8914-16913f50f583.jpg)

I like this one also, but the feeling is different ... I am seeing the landscape, I am not inside the river as the previous one.

**Comment by vjpixel** [comment]
@JoshuSantos please don't remember me about the ice cold water in Chapada Diamantina...

**Comment by vjpixel** [comment]
@bruquevedo I love this one!!!

**Comment by tiagobugarin** [comment]
> @vjpixel @tiagobugarin what about this one?
> 
> ![0002](https://user-images.githubusercontent.com/63117285/80142788-2159d700-8582-11ea-8914-16913f50f583.jpg)

This photo is very nice and also brings me some memories from places all around Brazil that share some resemblance. Although I liked the first one more, I understand this one is better aligned with bucoli.co's view.

**Comment by bruquevedo** [comment]
> 
> 
> > I prefer to have a landscape.
> 
> I understand the theme of bucolico's site as landscape (mostly), @vjpixel ... on the other hand, I think it creates a nice change of rhythm.
> 
> As a side note, @bruquevedo , maybe because of my previous trip to Capão, the closeup photo brought me back the memory of the coldness of the water. It wasn't something that I was expecting. I just felt. Funny, isn't it?

@JoshuSantos what you felt was really amazing. And I think that more people can fell that too. And I agree with the change of rhythm.  So here's what I propose, we can use the landscape one this time, because as you guys said it's more bucolico's style but we don't delete the one I sent first and we can use it two or three sprints from here. What do you think? @vjpixel @JoshuSantos @tiagobugarin

**Comment by bruquevedo** [comment]
> 
> 
> @vjpixel @tiagobugarin what about this one?
> 
> ![0002](https://user-images.githubusercontent.com/63117285/80142788-2159d700-8582-11ea-8914-16913f50f583.jpg)

@JoshuSantos @tiagobugarin @vjpixel do you agree with this image?

**Comment by tiagobugarin** [comment]
from me, this is the one for this week!

**Comment by vjpixel** [comment]
Yes!

**Comment by bruquevedo** [comment]
> 
> 
> > @vjpixel @tiagobugarin what about this one?
> > ![0002](https://user-images.githubusercontent.com/63117285/80142788-2159d700-8582-11ea-8914-16913f50f583.jpg)
> 
> @JoshuSantos @tiagobugarin @vjpixel do you agree with this image?

Ok so this is the image of the week

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by bruquevedo** [comment]
hey @tiagobugarin @vjpixel my suggestion to the image of the week is this one:

![BUCOLICO_04_v2](https://user-images.githubusercontent.com/63117285/80720118-d9333b00-8ad2-11ea-9bc5-96d065facc08.jpg)

**Comment by vjpixel** [comment]
I love it!

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by bruquevedo** [comment]
@tiagobugarin the image is already in our drive folder

**Comment by vjpixel** [comment]
Done!

**Comment by vjpixel** [comment]
Since we decided to create the image for the next week in this Sprint, I put the deadlines for both products in the description.

**Comment by bruquevedo** [comment]
My suggestion to sprint 0.0.5

![0001_BUCOLICO_SPRINT_005](https://user-images.githubusercontent.com/63117285/81186791-9cab8780-8f89-11ea-9678-d7aad27717a7.jpg)

**Comment by bruquevedo** [comment]
My suggestion to sprint 0.0.6

![002_BUCOLICO_SPRINT_006](https://user-images.githubusercontent.com/63117285/81186846-ae8d2a80-8f89-11ea-89c5-9699bc20298a.jpg)

**Comment by bruquevedo** [comment]
hey @vjpixel and @tiagobugarin above you can see the images I chose to milestone 0.0.5 and 0.0.6. Could you please review??

**Comment by vjpixel** [comment]
I think the one chose for 0.0.5 is a little monotonous and claustrophobopic. Can you propose another one?

**Comment by bruquevedo** [comment]
> 
> 
> I think the one chose for 0.0.5 is a little monotonous and claustrophobopic. Can you propose another one?

@vjpixel what about this one?

![003_BUCOLICO_SPRINT_005_V2](https://user-images.githubusercontent.com/63117285/81197006-26615200-8f96-11ea-94b5-ada588d7b04c.jpg)

**Comment by vjpixel** [comment]
Great!

**Comment by vjpixel** [comment]
Closing for 0.0.6.
