### ISSUE TITLE
As a user, I want an onboarding, so that I can experience the context of the photo

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#57]
_Deadline: Thu 11:00_

We believe that delivering a photo isn't enough for people to understand the bucoli.co's proposal.

We want to design and write an email related to the picture, so the people can feel immersed in the picture's context.

**Comment by bruquevedo** [comment]
The picture chosen for this week is in the issue #56

**Comment by vjpixel** [comment]
Since we need to finish work today, so we just focus on internal feedback on the weekend, I'm transferring this task to @bruquevedo .

**Comment by bruquevedo** [comment]
O céu azul pinta a paisagem
e o sol ilumina o caminho.
A natureza te convida a desacelerar
explorar, pensar livremente.
Respire fundo, devagar, sem pressa
sinta que chegou onde queria
e seja livre para permanecer
A liberdade te torna dono do seu próprio tempo.
Brisa, barulho de folhas, passarinhos
a água que corre, mansa, seguindo seu rumo
De mais um passo e descubra 
que o rio gelado te faz sentir vivo
Você se permite ir além e mergulhar?

Acesse bucoli.co para conhecer a foto da semana

*

A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site.
Para deixar seu comentário por lá basta clicar em feedback, no canto inferior direito da tela, e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!

Até a próxima semana :)

**Comment by vjpixel** [comment]
It's great! 

> A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site. Para deixar seu comentário por lá basta clicar em feedback, no canto inferior direito da tela, e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!

Since we're going to add a menu, there's one more step that we need to add in this paragraph.

Also, it missing some punctuation at the end of some sentences.

**Comment by bruquevedo** [comment]
O céu azul pinta a paisagem
e o sol ilumina o caminho.
A natureza te convida a desacelerar
explorar, pensar livremente.
Respire fundo, devagar, sem pressa
sinta que chegou onde queria
e seja livre para permanecer
A liberdade te torna dono do seu próprio tempo.
Brisa, barulho de folhas, passarinhos
a água que corre, mansa, seguindo seu rumo
De mais um passo e descubra
que o rio gelado te faz sentir vivo
Você se permite ir além e mergulhar?

Acesse bucoli.co para conhecer a foto da semana.

A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site.
Para deixar seu comentário por lá basta clicar no menu, no canto inferior direito da tela, depois em feedback e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!

Até a próxima semana :)

**Comment by bruquevedo** [comment]
> 
> 
> It's great!
> 
> > A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site. Para deixar seu comentário por lá basta clicar em feedback, no canto inferior direito da tela, e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!
> 
> Since we're going to add a menu, there's one more step that we need to add in this paragraph.
> 
> Also, it missing some punctuation at the end of some sentences.

O céu azul pinta a paisagem
e o sol ilumina o caminho.
A natureza te convida a desacelerar
explorar, pensar livremente.
Respire fundo, devagar, sem pressa
sinta que chegou onde queria
e seja livre para permanecer
A liberdade te torna dono do seu próprio tempo.
Brisa, barulho de folhas, passarinhos
a água que corre, mansa, seguindo seu rumo
De mais um passo e descubra
que o rio gelado te faz sentir vivo
Você se permite ir além e mergulhar?

Acesse bucoli.co para conhecer a foto da semana.

*

A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site.
Para deixar seu comentário por lá basta clicar no menu, no canto inferior direito da tela, depois em feedback e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!

Até a próxima semana :)
_________________________________

what about now? @vjpixel @tiagobugarin @JoshuSantos

**Comment by bruquevedo** [comment]
@tiagobugarin could you please review it?

**Comment by tiagobugarin** [comment]
It's great! closing and moving.

**Comment by bruquevedo** [comment]
Reopened the issue after pixel's comment in issue #61 

Now, my suggestion to the text:
Temos novidades: adicionamos uma ferramenta de feedback diretamente no site.
Deixe seu comentário por lá clicando no menu, no canto inferior direito da tela, e depois em feedback. Você também pode comentar e votar na sugestão de outras pessoas. Dessa forma, iremos avaliar todas as sugestões e comentários para decidir quais melhorias implementar no nosso site para melhorar a sua experiência. 

@vjpixel @tiagobugarin @JoshuSantos

**Comment by vjpixel** [comment]
Great!

**Comment by tiagobugarin** [comment]
uma sugestão

> Você também pode comentar e votar na sugestão de outras pessoas. Dessa forma, iremos avaliar todas as sugestões e comentários para decidir quais melhorias implementar no nosso site para aprimorar a sua experiência.

Você também pode colaborar comentando e votando em outras sugestões. Tudo será considerado enquanto decidimos quais mudanças implementar no bucoli.co para melhorar sua experiência.

**Comment by bruquevedo** [comment]
Onboarding text to the next send (04/05)

O colorido do céu anuncia
que lá se vai mais um dia…
para um novo começar.
O mar bate calmo nas pedras
como quem sabe
que não é preciso se apressar.
Feche os olhos, reflita sobre o que passou
e pense no que está por vir.
Você pode
recomeçar, continuar,
retomar, progredir.
Não tenha medo, respire fundo
e respeite seu tempo.
Permita-se enxergar o horizonte
que há dentro de você.

. . .

Comece seu dia acessando bucoli.co para ver a imagem da semana.

Queremos ampliar nossa comunidade. Por isso, em breve iremos divulgar o bucoli.co em redes sociais. Você acredita que o site está pronto para ser divulgado? Se não, o que você acha que falta? Deixe seu feedback.

Seus comentários e sugestões ajudam a nos guiar.

Até a próxima imagem! :)

P.S.: Acesse a ferramenta de feedback clicando no menu.

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by vjpixel** [comment]
It's great!

**Comment by bruquevedo** [comment]
Onboarding text to sprint 0.0.5. You can see the image related in the issue #56 

O caminho que se vê à frente
te convida a ter coragem
para superar desafios.
Inspire-se pelo ambiente que te cerca,
tenha força, passos firmes
e experimente desbravar o desconhecido.
Pare por um momento, 
contemple o verde suave 
que brota por entre as rochas. 
É a natureza te mostrando
que sempre é possível seguir em frente.
Respire fundo, trace sua rota e descubra 
o que está além do que se pode enxergar. 

. . .

Veja a imagem da semana acessando bucoli.co.

Já temos algumas sugestões na área de feedback. Depois de contemplar a foto dessa semana, te convidamos a acessar, votar e comentar nas sugestões que você se identifica.  

Até a próxima imagem! :)

P.S.: Acesse a ferramenta de feedback clicando no menu.

**Comment by vjpixel** [comment]
Great!
