### ISSUE TITLE
As a user, I want to get curious about the picture, so I get motivated to see it

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#58]
_0.0.5 Deadline: Thu 11:00_

_0.0.6 Deadline: Fri 18:00_

The team believes that having the new picture on the email will make users engaged in visiting bucoli.co.

We want to have a personalized logo with the new picture.

**Comment by bruquevedo** [comment]
![TOPO-BUCOLICO-03](https://user-images.githubusercontent.com/63117285/80257646-c692af00-8657-11ea-8818-1d2ed73a9193.jpg)

this is this week's custom logo

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by vjpixel** [comment]
I love that the part chose makes me feel I'm going to see a waterfall, but then I see a river.

**Comment by bruquevedo** [comment]
![TOPO-BUCOLICO-04](https://user-images.githubusercontent.com/63117285/80729410-9ecf9b00-8ade-11ea-992f-cbeb7a829d51.jpg)

@vjpixel what do you think about this heading?

**Comment by vjpixel** [comment]
I love it!

**Comment by vjpixel** [comment]
Since we decided to create the image for the next week in this Sprint, I put the deadlines for both products in the description.

**Comment by bruquevedo** [comment]
personalized image to sprint 0.0.5

![TOPO-BUCOLICO-SPRINT-005](https://user-images.githubusercontent.com/63117285/81337096-db703900-9080-11ea-9d08-0eca82a17a1d.jpg)

**Comment by vjpixel** [comment]
Great!

**Comment by bruquevedo** [comment]
personalized heading for sprint 0.0.6. You can see the related image in the issue #56 

![TOPO-BUCOLICO-SPRINT-006](https://user-images.githubusercontent.com/63117285/81418594-483c0f80-9123-11ea-9fb2-8a9573359ea1.jpg)

**Comment by vjpixel** [comment]
Great!
