### ISSUE TITLE
As an user, I want to be able to easily see the menu, so I can find it

### ISSUE THREAD

**Issue by tiagobugarin** [memeLab/bucoli.co#6]
_Deadline: Fri 18:00_

We're going to have bright and dark photos behind the text.

We need a solution that makes the menu easy to see in every context.

**Comment by vjpixel** [comment]
We decided to have themes for light and dark backgrounds, and a different theme for mixed backgrounds.

The theme for light background will have dark font colour, and the theme for dark background will do the opposite.

The theme for mixed background will have contours on the letters.

**Comment by JoshuSantos** [comment]
I believe I solved that in #27 ... take a look, @tiagobugarin and @bruquevedo

**Comment by vjpixel** [comment]
I just updated the description.

**Comment by JoshuSantos** [comment]
@tiagobugarin , the usual solution for this is a WHITE text with a tiny drop shadow. This way ... when we have a dark photo, the whiteness of the text appears... when we have a light photo, the drop shadow helps the text to pop up.

**Comment by tiagobugarin** [comment]
> @tiagobugarin , the usual solution for this is a WHITE text with a tiny drop shadow. This way ... when we have a dark photo, the whiteness of the text appears... when we have a light photo, the drop shadow helps the text to pop up.

considering there will only be a menu button at first and, on click, show up the menu items, do you still think the drop shadow approach is valid?
that drop shadow would be leaning on a dark or a light color?

**Comment by tiagobugarin** [comment]
So, @JoshuSantos, would you please review this issue?

**Comment by vjpixel** [comment]
I just tested on mobile,  l and it's hard tip see the menu.

**Comment by vjpixel** [comment]
Same problem on the about page.

Also, the photo doesn't fit the screen, leaving a black border.

**Comment by vjpixel** [comment]
I answered by email and the photos weren't attached, so I'm attaching them now.

![Screenshot_20200425-183850_Firefox](https://user-images.githubusercontent.com/1034796/80291696-37080180-8726-11ea-8a93-99423d15268d.jpg)

![Screenshot_20200425-184222_Firefox](https://user-images.githubusercontent.com/1034796/80291697-38392e80-8726-11ea-8c2c-0a7cf3891db8.jpg)

**Comment by tiagobugarin** [comment]
think it is fixed now...

**Comment by tiagobugarin** [comment]
@bruquevedo or @vjpixel , would one of you please review?

**Comment by vjpixel** [comment]
It's good enough for this sprint, but I propose we improve it in the next.
