### ISSUE TITLE
As a staff member, I want to be sure that the email is ready, so I know we can send the final version

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#61]
_0.0.4 Deadline: Tue 10:00_

_0.0.5 Deadline: Thu 16:00_

_Revision protocol deadline: Fri 12:00_

Test with different people if the email is arriving and looking/working as it should.

1. We need to send a test email to the team so everyone can review it before we send the final version.

2. We want to improve this issue including a revision protocol.

**Comment by vjpixel** [comment]
@bruquevedo please ask the team to put the feedback here, so everyone can discuss it.

**Comment by bruquevedo** [comment]
hey @vjpixel @JoshuSantos and @tiagobugarin I just sent the e-mail test. As soon as possible please give your feedback here. Tks :)

**Comment by bruquevedo** [comment]
I received the e-mail in the inbox. Link is working and everthing is ok to me

**Comment by tiagobugarin** [comment]
The email reached the inbox and the link worked.
Now I am working on making the menu button so the text can mean what it says! :)

**Comment by vjpixel** [comment]
There are two things I noticed, both in this paragraph.

>A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site. Para deixar seu comentário por lá basta clicar no menu, no canto inferior direito da tela, depois em feedback e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!

1. There's a bucoli.co (not tracked) link on it. I propose to rewrite the phrase so we don't have a system turning bucoli.co to a link.

2. Reading the paragraph in the email, I noticed it can be more strong when asking for the people to include feedback. I propose to rewrite it asking directly people to write feedback - and tell them what we're going to make with it.

**Comment by bruquevedo** [comment]
> 
> 
> There are two things I noticed, both in this paragraph.
> 
> > A sua opinião nos ajuda a deixar a experiência com o bucoli.co cada vez melhor. E para facilitar esse processo, adicionamos uma ferramenta de feedback diretamente no site. Para deixar seu comentário por lá basta clicar no menu, no canto inferior direito da tela, depois em feedback e deixar a sua sugestão. Vamos adorar ler o que você tem para nos dizer!
> 
>     1. There's a bucoli.co (not tracked) link on it. I propose to rewrite the phrase so we don't have a system turning bucoli.co to a link.
> 
>     2. Reading the paragraph in the email, I noticed it can be more strong when asking for the people to include feedback. I propose to rewrite it asking directly people to write feedback - and tell them what we're going to make with it.

I reopened issue #57 and commented there my new suggestion to your observation

**Comment by tiagobugarin** [comment]
>     1. There's a bucoli.co (not tracked) link on it. I propose to rewrite the phrase so we don't have a system turning bucoli.co to a link.

the problem here is that it was not made in to a link from within the MailChimp system, then it goes out as a normal text and then the mail client interprets it as a link.
my proposal is to make the `bucolli.co`  text into a link so that it will be trackable after leaving the MailChimp system.

always remember that `bucoli.co` as a name is a link reference and like all links it will be looked upon from different systems and made into a link if it is not already. so, stay in front of the many systems and make it a link before so you can control the behavior instead of the other parties.

**Comment by JoshuSantos** [comment]
PROs:
1. The email was in my Inbox and the link took me to bucoli.co

CONs:
1. The image on the header of the email is the NEW image. The image on the site is from last week.
2. I did not see the feedback menu/button in order to test and use it.

**Comment by vjpixel** [comment]
@JoshuSantos 

Since we're testing the final email, there's no way to point it to the alpha version. Pretend the link you're receiving is `alpha.bucoli.co`, and both the cons you listed are gone.

**Comment by bruquevedo** [comment]
I received feedback from everybody and already changed what you suggested. So we can consider that the email is ready to be sent to testers on monday 8am

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by vjpixel** [comment]
Can you please send it again so I can review the new version? @bruquevedo

**Comment by bruquevedo** [comment]
ok

**Comment by bruquevedo** [comment]
I received the email in the inbox and everthing is ok

**Comment by tiagobugarin** [comment]
inbox and link tracked working as it should.

**Comment by bruquevedo** [comment]
@vjpixel could you please review the issu?

**Comment by bruquevedo** [comment]
E-mail test was sent with the new email as you can see in issue #84

**Comment by bruquevedo** [comment]
I received it in the inbox (uhu). Both links are working but the second link was automatically created by mailchimp so I need to fix it to a traceable link, right?

**Comment by tiagobugarin** [comment]
test email with new "from" address received in the inbox and tracked link working

everything in its right place

**Comment by vjpixel** [comment]
The email text is missing its final dot.

**Comment by bruquevedo** [comment]
> 
> 
> The email text is missing its final dot.

corrected

@vjpixel could you please review this issue?

**Comment by vjpixel** [comment]
Also, the second bucoli.co link is not tracked.

**Comment by vjpixel** [comment]
Can you please send the email again so I can check? @bruquevedo

**Comment by vjpixel** [comment]
Also, I just noticed that when I click on "Veja este email em seu navegador" it opens a screen that, if I click on "Past Issues" it shows all emails (including the tests.

I think we need to delete "Past Issues" from the screen.

![Screenshot from 2020-04-30 17-35-12](https://user-images.githubusercontent.com/1034796/80756523-0e5a8000-8b09-11ea-8955-d8222da182bc.png)

**Comment by bruquevedo** [comment]
> 
> 
> Also, the second bucoli.co link is not tracked.

@tiagobugarin could you please help me make the second link trackble? I tryed to do it myself but I'm missing something

**Comment by bruquevedo** [comment]
> 
> 
> Also, I just noticed that when I click on "Veja este email em seu navegador" it opens a screen that, if I click on "Past Issues" it shows all emails (including the tests.
> 
> I think we need to delete "Past Issues" from the screen.
> 
> ![Screenshot from 2020-04-30 17-35-12](https://user-images.githubusercontent.com/1034796/80756523-0e5a8000-8b09-11ea-8955-d8222da182bc.png)

I'm going to check it and then send the email test again

**Comment by bruquevedo** [comment]
> 
> 
> Also, I just noticed that when I click on "Veja este email em seu navegador" it opens a screen that, if I click on "Past Issues" it shows all emails (including the tests.
> 
> I think we need to delete "Past Issues" from the screen.
> 
> ![Screenshot from 2020-04-30 17-35-12](https://user-images.githubusercontent.com/1034796/80756523-0e5a8000-8b09-11ea-8955-d8222da182bc.png)

@tiagobugarin could you please help me how to delete this option?

**Comment by bruquevedo** [comment]
@vjpixel sent you a new test yesterday. Could you please review this issue?

**Comment by tiagobugarin** [comment]
that bar on the top where you can click to see this screen cannot be selectivelly adjusted.
i can (and did) remove it all together, thou.
try again the "veja este email no navegador" link and give a feedback if it is ok with you, @bruquevedo and @vjpixel

**Comment by bruquevedo** [comment]
> 
> 
> that bar on the top where you can click to see this screen cannot be selectivelly adjusted.
> i can (and did) remove it all together, thou.
> try again the "veja este email no navegador" link and give a feedback if it is ok with you, @bruquevedo and @vjpixel

Great! Now it only opens the email of the week.

**Comment by vjpixel** [comment]
There's a bug on our emails, described in #85.
 
I propose that we fix the bug and send the test again.

**Comment by bruquevedo** [comment]
@vjpixel can I already send it?

**Comment by vjpixel** [comment]
We agreed to discuss before sending it.

**Comment by bruquevedo** [comment]
We fixed the problem in the issue #85 as you can check there. 
I just sent the email test to our staff. Please @tiagobugarin and @vjpixel review the email. Check if the first link is sending to the permalink and the second directly to bucoli.co
If you want, you can check if the other permalinks are working to. 
Soon me and @tiagobugarin will do a protocol to the e-mail review. But now you can pay attention in what I said above. Please put you answers in this issue.

**Comment by tiagobugarin** [comment]
email received at the inbox. the two links to `bucoli.co` at the body of the email are being tracked and are working correctly.

**Comment by bruquevedo** [comment]
- Email received at the inbox;
- The two links are ok;
- The "veja esse e-mail no seu navegador" link working correctly;

**Comment by vjpixel** [comment]
Same here.

**Comment by vjpixel** [comment]
Since we decided to create the image for the next week in this Sprint, I put the deadlines for both products in the description.

**Comment by vjpixel** [comment]
Since the revision protocol will be implemented inside this issue, I included it (and deadline) in the description.

**Comment by bruquevedo** [comment]
@tiagobugarin and @vjpixel I sent the email test for sprint 0.0.5 yesterday.

Please follow this steps to check the email (this is my suggestion of revision protocol):

- Did you receive the email in the inbox?;
- Ts the "Veja este e-mail no seu navegador" link working correctly?;
- Is the personalized heading related to the chosen image for this sprint?;
- Is the onboarding text related to the chosen image for this sprint?;
- Is the bucoli.co link sending to the correctly permalink number?;
- Feel free to say anything else that you think needs to be corrected.

**Comment by bruquevedo** [comment]
> 
> 
> @tiagobugarin and @vjpixel I sent the email test for sprint 0.0.5 yesterday.
> 
> Please follow this steps to check the email (this is my suggestion of revision protocol):
> 
>     * Did you receive the email in the inbox?;
> 
>     * Ts the "Veja este e-mail no seu navegador" link working correctly?;
> 
>     * Is the personalized heading related to the chosen image for this sprint?;
> 
>     * Is the onboarding text related to the chosen image for this sprint?;
> 
>     * Is the bucoli.co link sending to the correctly permalink number?;
> 
>     * Feel free to say anything else that you think needs to be corrected.

**Comment by bruquevedo** [comment]
> 
> 1- Did you receive the email in the inbox?;
> 2- Ts the "Veja este e-mail no seu navegador" link working correctly?;
> 3- Is the personalized heading related to the chosen image for this sprint?;
> 4- Is the onboarding text related to the chosen image for this sprint?;
> 5- Is the bucoli.co link sending to the correctly permalink number?;
> 6- Feel free to say anything else that you think needs to be corrected.

1 - Yes;
2 - Yes;
3 - Yes;
4 - Yes;
5 - No, it needs to be corrected to number 7, because number 6 is from the past sprint;

**Comment by vjpixel** [comment]
1 - Yes;
2 - Yes;
3 - Yes;
4 - Yes;
5 - No, as @bruquevedo said before.
6 - In the end, I propose to use an exclamation mark tp fnish the sentence: "Até a próxima imagem!"

I'll wait for the link so I can review it again. I propose you just ask for people to review after you have reviewed yourself and consider it done.

**Comment by tiagobugarin** [comment]
> @tiagobugarin and @vjpixel I sent the email test for sprint 0.0.5 yesterday.
> 
> Please follow this steps to check the email (this is my suggestion of revision protocol):
> 
> 1- Did you receive the email in the inbox?;
> 2- Ts the "Veja este e-mail no seu navegador" link working correctly?;
> 3- Is the personalized heading related to the chosen image for this sprint?;
> 4- Is the onboarding text related to the chosen image for this sprint?;
> 5- Is the bucoli.co link sending to the correctly permalink number?;
> 6- Feel free to say anything else that you think needs to be corrected.

Concerning to the second email:

1. Yes
2. Yes
3. Yes
4. Yes
5. Yes
6. Yes... oh wait, not a yes/no question... nothing to add at this point.

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by vjpixel** [comment]
I checked, and it's working great!
