### ISSUE TITLE
As a user, I want to receive a response to the feedback I sent, so I feel engaged in sending more feedback

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#64]
_Deadline: Mon 12:00_

Answering users' feedback is both a way to tell them we're interested in their response and a way to keep them engaged.

We need to respond to feedback we receive.

**Comment by vjpixel** [comment]
I just updated the description and the deadline.

**Comment by bruquevedo** [comment]
feedbacks are being answered directly in the tool on the website as the community leaves its comments
