### ISSUE TITLE
As a staff member, I want to have feedback organized, so I can quickly analyze it

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#65]
_Deadline: Tue 18:00_

Having a document organizing all the feedback help the team to easily find and analyze the feedback.

Also, the document has insights from the feedbacks that help us to define what to do next.

We need to organize the feedbacks in the document.

Also, we need to update the User Journey document including who answered the email.

**Comment by bruquevedo** [comment]
once we implemented the feedback tool as you can see in the issue #54 we don't need to organize the feedback in a spreadsheet anymore

**Comment by bruquevedo** [comment]
@vjpixel could you please review this issue?

**Comment by vjpixel** [comment]
I just marked it as invalid.
