### ISSUE TITLE
As a staff member, I need to have a lean canvas, so I can align my understanding of bucoli.co

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#67]
We agreed on everyone creating a lean canvas, and then we meet and create a final version.

@vjpixel will send a link with an explanation of how to create one.

We need to have a finished lean canvas.

**Comment by vjpixel** [comment]
I just shared the explanation on Slack. Can you please confirm, @tiagobugarin ?

**Comment by tiagobugarin** [comment]
i confirm the lean canvas instructions has been shared with the team. closing and moving.
