### ISSUE TITLE
As a staff member, I want a model for Sprint Review slides so I can create a presentation easily.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#69]
_Deadline: Mon 18:00_

One of the things we agreed to improve last week was the Sprint Review. We decided to create presentations that show (visually) what we've done. We expect that this will add value to the meeting, bringing more information, and will make it more objective.

We need to have a model for the slides.

**Comment by vjpixel** [comment]
@tiagobugarin @bruquevedo

**Comment by vjpixel** [comment]
I'm proposing this way because it's simple (we an do it very fast) and I think it's as effective as creating slides.

**Comment by bruquevedo** [comment]
ok I agree

**Comment by tiagobugarin** [comment]
fine by me too
