### ISSUE TITLE
As a user, I want to have a subscription form so I can receive an email when there's a new photo.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#73]
_Deadline: Thu 12:00_

Since we're aiming to increase the number of subscribers, having a subscription form will automatize the process. It will make it simpler for both users and the staff.

We need to include a subscription form.

**Comment by tiagobugarin** [comment]
mailchimp's subscription added. must test to see if it is working properly and do some design and text changes.

**Comment by vjpixel** [comment]
I subscribed using test email account, but I didn't receive the confirmation.

**Comment by vjpixel** [comment]
Also, "Assinar" in the menu, is starting with uppercase, not following the pattern.

**Comment by vjpixel** [comment]
I checked Slack, and MailChimp says that the email address is subscribed. So I think that the only thing that is missing is to send the confirmation email to the user.

**Comment by tiagobugarin** [comment]
> So I think that the only thing that is missing is to send the confirmation email to the user.

hmmm i think i saw something like that in the settings at mailchimp... will give a better look there

**Comment by tiagobugarin** [comment]
many clicks later it is done.
tested subscribing and unsubscribing.

curious thing: after i unsubscribed my email e other details were kept there but with an "unsubscribed" notation.

will give a look at data retention some other day. maybe enabling some GDPR features this can be mitigated.

**Comment by tiagobugarin** [comment]
@vjpixel or @bruquevedo woulld any of you two review this?

**Comment by bruquevedo** [comment]
I followed all the steps
1) fill the form;
2) An email is sent to confirm my subscription;
3) Received the email in the promotion tab;
4) Clicked in a link to confirm my subscription;
5) The link directs to a web link where I confirmed that I'm a human
6) Checked in the mailchimp and the email that I signed up is in the audience list
