### ISSUE TITLE
As a staff member, I want to have the same vocabulary as the team so we can have more efficient communication.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#74]
_Deadline: Thu 20:00_

We have a constant effort to align our vocabulary terminology in order to have clear communication.

This is a recurring task that'll be in every sprint where it's needed, with different vocabulary.

We need to have a common understanding of software versioning.

**Comment by bruquevedo** [comment]
I took a look in the two materials and I think that for an initial understanding is enough

**Comment by vjpixel** [comment]
I just updated the description.

**Comment by vjpixel** [comment]
My proposal is to use Semantic Versioning: https://semver.org/

What do you think @tiagobugarin?

**Comment by vjpixel** [comment]
Also, I propose we rename the Milestones. Instead of using "0.0.1", "0.0.2", and so on, to use the email related to it. I propose we use numbers in full "one", two", and so on. This way, the next Milestone will be "seven". What do you think? @bruquevedo

**Comment by bruquevedo** [comment]
@vjpixel I agree. I think that this way will be easier to comunicate about the milestone in the different places we need

**Comment by tiagobugarin** [comment]
> My proposal is to use Semantic Versioning: https://semver.org/
> 
> What do you think @tiagobugarin?

I like semver very much. we could use it!

**Comment by tiagobugarin** [comment]
> Also, I propose we rename the Milestones. Instead of using "0.0.1", "0.0.2", and so on, to use the email related to it. I propose we use numbers in full "one", two", and so on. This way, the next Milestone will be "seven". What do you think? @bruquevedo

A few weeks back I would not like this idea but now I feel it can better our understanding of the process. BTW, makes it very clear about the number in the permalink.

**Comment by vjpixel** [comment]
Since we're settled, I'm closing this one.
