### ISSUE TITLE
As a user, I want an updated About text so I can better understand bucoli.co.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#75]
_Deadline: Thu 20:00_

The text we have now is long and the information about the update schedule is outdated.

We need a new version of the text.

**Comment by vjpixel** [comment]
@bruquevedo @tiagobugarin, can you please share here the texts you written?

**Comment by bruquevedo** [comment]
O bucoli.co é um projeto que cria uma experiência que te convida e desacelerar.
A proposta é que você acesse o site e veja uma bela imagem de paisagem. Não há inúmeros botões, ou uma grande galeria para você navegar, nem outras distrações. 
Sua tela se transforma em um portal para um lugar prazeroso e tranquilo. 
Você tem uma foto para contemplar, explorar, prestar atenção aos detalhes. Na cor do céu, no movimento da água, na copa das árvores, no horizonte. 
É um momento de quebra da rotina. Propomos que você pare por alguns instantes e desacelere o ritmo frenético ao qual o trabalho e o excesso de informações te levam.

**Comment by vjpixel** [comment]
Fugere urbem é uma expressão em latim que significa "fugir da cidade". Originalmente usada pelo escritor latino Horácio, foi adotada como lema pela literatura árcade para simbolizar o poeta que se desloca da vida agitada da cidade e vai para a calma zona rural.

A proposta de bucoli.co é aproveitar alguns instantes do enorme tempo que passamos olhando para telas para fugir da poluição visual urbana. A cada semana, há uma nova imagem de uma paisagem bucólica, de artistas que convidamos. É uma oportunidade de fugir um pouco do estresse do confinamento e voltar às origens.

Fugere urbem!

**Comment by vjpixel** [comment]
I think the text I wrote works best on the website and @bruquevedo text works best outside (on social media, for example). So my proposal is to use my text in the About page and Bruna's on #79.

**Comment by bruquevedo** [comment]
I agree

**Comment by tiagobugarin** [comment]
i also agree with @vjpixel
