### ISSUE TITLE
As a old staff member, I want my user removed, so I don't receive messages that don't interest me.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#76]
_Deadline: Thu 20:00_

Since Joshu and Vanessa left the team, we need to check with them if they want to keep the users/accesses in GitHub, Slack, and Drive.

We need to ask them what accesses they want to keep and remove the ones they don't.

**Comment by vjpixel** [comment]
@tiagobugarin do you remember any other system else they have users for bucoli.co?

**Comment by vjpixel** [comment]
I'm waiting for an answer from @JoshuSantos

**Comment by tiagobugarin** [comment]
> @tiagobugarin do you remember any other system else they have users for bucoli.co?

listing every other thing i can remember:

sendpulse
mailchimp
google analytics
optimizely
userreport

**Comment by vjpixel** [comment]
I didn't find users from them on SendPulse, MailChimp, Analytics, Optimizely, or UserReport.

I removed them from the Slack channels, from the Github repository, and from the Drive folder.

can you please review @tiagobugarin

**Comment by tiagobugarin** [comment]
I can confirm the removal of their profiles from the Google Drive shared folder. So this on is a go.
The Slack channels I can confirm the removal of almost all channels. They are still members of the groups `#general` and `#random". If this is as intended, then this one is a second go.
I cannot, make any assesment on the Github repository as can't confirm. I see my self, and @vjpixel but I don't see @bruquevedo, vanessa and joshu. If I can't see bruna, and I know she is in the project, I can trust that the other two are not... so this on is a hold from me.

So, summarizing:
* Google Drive Shared Folder: ok
* Slack Channles: ok (if it is ok to have them at `#general` and ``$random`)
* Github Repositoy: not sure

**Comment by vjpixel** [comment]
@tiagobugarin 

It's ok to have them on Slack. We have other users there too.

Can you please try this "https://github.com/memeLab/bucoli.co/settings/access" link? It should show Bruna's user but not Joshu's.

**Comment by tiagobugarin** [comment]
I don't know if I missied this spot earlier or if that bump in my permissions here in github the other day allowed me to see that now but the fact is that with this panel I can confirm we are just us three.

so now, summarizing:

- Google Drive Shared Folder: ok
- Slack Channles: ok
- Github Repositoy: ok

with this, i close and move this issue to Done
