### ISSUE TITLE
As a user, I don't want to be a tester, so that I don't get annoyed by the staff reaching to me.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#78]
_Deadline: Fri 16:00_

We know that most of the Testers are not engaged, so we decided to turn them into Community and create a new Testers' group later.

With this change, some Testers that had their accounts disabled can have them enabled again.

We need to rename the testers' database and reenable the tester's accounts that were disabled.

**Comment by vjpixel** [comment]
I just updated the description.

**Comment by vjpixel** [comment]
Also, please move Joshu and Vanessa from the Staff to the Community group.

**Comment by bruquevedo** [comment]
Done. @tiagobugarin could you please review this issue?

**Comment by tiagobugarin** [comment]
its done.

closing and moving
