### ISSUE TITLE
As a user, I want to have an updated website, so I can see the new picture.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#81]
_0.0.4 Deadline: Tue 10:00_

_0.0.5 Deadline: Sun 20:00_

We discussed that a deployment issue/task is important to mark the end of the development process.

We need to merge the branch Alpha to Master, and deploy Master.

**Comment by tiagobugarin** [comment]
alpha already has:
* new image
* about inside the index (no longer another page)
* everything working as a modal like block
* new text formating for the about text
* new about text and updated staff members' list
* subscribe form to receive bucoli.co's email every week

**Comment by tiagobugarin** [comment]
i believe alpha is ready for this sprint. @vjpixel would you review?

**Comment by vjpixel** [comment]
Assinar and Sobre are working as supposed, just showing one content at a time. But the Feedback is opening on top of the other pages.

Is there a way to change this to have only one behavior?

**Comment by vjpixel** [comment]
Since there are people accessing the website from the last email, we need to deploy it just before we send the next email, so the deadline initially proposed is wrong.

I propose to the deploy to be made _Sunday at 20:00_ (so there's time to other team members to review and to the developer to fix an eventual problem).

**Comment by vjpixel** [comment]
@tiagobugarin ping

**Comment by tiagobugarin** [comment]
> Assinar and Sobre are working as supposed, just showing one content at a time. But the Feedback is opening on top of the other pages.
> 
> Is there a way to change this to have only one behavior?

fixed.

**Comment by tiagobugarin** [comment]
Following #85 the site has been deployed at 10h35, May 5th 2020.
Closing and moving.

**Comment by vjpixel** [comment]
I updated the description to reflect what was said in https://github.com/memeLab/bucoli.co/issues/80#issuecomment-624256022

**Comment by vjpixel** [comment]
I want to propose a step after deploy, to manually create a snapshot on the Internet Archive. The feature allows to "capture a web page as it appears now for use as a trusted citation in the future."

To do This:
1. Go to https://archive.org/web/
2. Fill Save Page Now with http://bucoli.co

@tiagobugarin, if you agree, I will put this step in the description of this issue.

**Comment by vjpixel** [comment]
Since we decided to create the image for the next week in this Sprint, I put the deadlines for both products in the description.

**Comment by tiagobugarin** [comment]
> I want to propose a step after deploy, to manually create a snapshot on the Internet Archive. The feature allows to "capture a web page as it appears now for use as a trusted citation in the future."
> 
> To do This:
> 
>     1. Go to https://archive.org/web/
> 
>     2. Fill Save Page Now with http://bucoli.co
> 
> 
> @tiagobugarin, if you agree, I will put this step in the description of this issue.

I like that!

**Comment by tiagobugarin** [comment]
> Since there are people accessing the website from the last email, we need to deploy it just before we send the next email, so the deadline initially proposed is wrong.
> 
> I propose to the deploy to be made _Sunday at 20:00_ (so there's time to other team members to review and to the developer to fix an eventual problem).

Makes total sense to me. Sun 20h is good to me

**Comment by vjpixel** [comment]
OP?

**Comment by tiagobugarin** [comment]
> OP?

Original Post

**Comment by tiagobugarin** [comment]
Made the first manual publication to the Internet Archive's WayBack Machine

**Comment by vjpixel** [comment]
Great!
