### ISSUE TITLE
As a staff member, I want an @bucoli.co email so I can have an independent email.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#84]
_Deadline: Thu 20:00_

We miss having a @bucoli.co email. The username we decided is oi.

We need a @bucoli.co email.

**Comment by tiagobugarin** [comment]
changes to the bucoli.co DNS records were made. let the tests begin!!!

@vjpixel @bruquevedo

**Comment by bruquevedo** [comment]
good!

**Comment by tiagobugarin** [comment]
@bruquevedo can you review this one?

**Comment by bruquevedo** [comment]
I sent the email test to our staff using it so yes, we have oi@bucoli.co email working :)

**Comment by vjpixel** [comment]
But

**Comment by tiagobugarin** [comment]
> But to check it we need to confirm that we can _receive_ email on this account.

ok. replying from the malichimp test sent earlier

**Comment by tiagobugarin** [comment]
@bruquevedo sent a reply from the newest campaing test email sent from the new mail address. do you confirm receiving it? would you be kind to review again this issue?

**Comment by bruquevedo** [comment]
Yes, I received!
