### ISSUE TITLE
As a staff member, I want an organized schedule, so I can remember what I need to act now.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#86]
_Deadline: Tue 18:00_

We're always adjusting our way of communicating. We use Slack to have reminders of due tasks and Calendar to organize meetings.

We need to have reminders of the tasks due today and tomorrow on Slack, and meetings scheduled on Calendar.

**Comment by vjpixel** [comment]
Model created last week:

`/remind #bucolico "Tasks with deadlines today for @Tiago #73 #72, for @vjpixel #74 #75 #76, for @Bruna Quevedo #56 # 59 #57 #58" Thu 9:00`

**Comment by vjpixel** [comment]
I'll write all sentences for this week's reminders here.

**Tuesday 20:00**

`/remind @Bruna Quevedo "Tasks due tomorrow
9h https://github.com/memeLab/bucoli.co/issues/62
16h https://github.com/memeLab/bucoli.co/issues/56
" today 20:00`

**Wednesday 9:00**

`/remind @Bruna Quevedo "Tasks due today
9h https://github.com/memeLab/bucoli.co/issues/62
16h https://github.com/memeLab/bucoli.co/issues/56
" Wed 9:00`

**Wednesday 17:00**

`/remind @Tiago "Tasks due tomorrow
11h https://github.com/memeLab/bucoli.co/issues/80
20h https://github.com/memeLab/bucoli.co/issues/60
" Wed 17:00`

`/remind @Bruna Quevedo "Tasks due tomorrow
11h https://github.com/memeLab/bucoli.co/issues/57
11h https://github.com/memeLab/bucoli.co/issues/58
16h https://github.com/memeLab/bucoli.co/issues/61
18h https://github.com/memeLab/bucoli.co/issues/56
" Wed 17:00`

`/remind @vjpixel "Tasks due tomorrow
20h https://github.com/memeLab/bucoli.co/issues/76
20h https://github.com/memeLab/bucoli.co/issues/74
" Wed 17:00`

**Thursday 9:00**

`/remind @Tiago "Tasks due today
11h https://github.com/memeLab/bucoli.co/issues/80
20h https://github.com/memeLab/bucoli.co/issues/60
" Thu 9:00`

`/remind @Bruna Quevedo "Tasks due today
11h https://github.com/memeLab/bucoli.co/issues/57
11h https://github.com/memeLab/bucoli.co/issues/58
16h https://github.com/memeLab/bucoli.co/issues/61
18h https://github.com/memeLab/bucoli.co/issues/56
" Thu 9:00`

`/remind @vjpixel "Tasks due today
20h https://github.com/memeLab/bucoli.co/issues/76
20h https://github.com/memeLab/bucoli.co/issues/74
" Thu 9:00`

**Thursday 17:00**

`/remind @Tiago "Tasks due tomorrow
12h https://github.com/memeLab/bucoli.co/issues/61
15h https://github.com/memeLab/bucoli.co/issues/81
18h https://github.com/memeLab/bucoli.co/issues/87
" Thu 17:00`

`/remind @Bruna Quevedo "Tasks due tomorrow
12h https://github.com/memeLab/bucoli.co/issues/61
18h https://github.com/memeLab/bucoli.co/issues/58
" Thu 17:00`

**Friday 9:00**

`/remind @Tiago "Tasks due today
12h https://github.com/memeLab/bucoli.co/issues/61
15h https://github.com/memeLab/bucoli.co/issues/81
18h https://github.com/memeLab/bucoli.co/issues/87
" Fri 9:00`

`/remind @Bruna Quevedo "Tasks due today
12h https://github.com/memeLab/bucoli.co/issues/61
18h https://github.com/memeLab/bucoli.co/issues/58
" Fri 9:00`

**Friday 17:00**

`/remind @Bruna Quevedo "Tasks due Monday
9h https://github.com/memeLab/bucoli.co/issues/62
" Fri 17:00`

**Sunday 17:00**

`/remind @Bruna Quevedo "Tasks due Monday
9h https://github.com/memeLab/bucoli.co/issues/62
" Sun 17:00`

**Monday 8:00**

`/remind @Bruna Quevedo "Tasks due today
9h https://github.com/memeLab/bucoli.co/issues/62
" Mon 8:00`

**Comment by vjpixel** [comment]
@bruquevedo can you please review?

I suggest you check:
* if I said "today" at the beginning of the day and "tomorrow" in the end
* check if the days and times on bold and in the messages are the same.

**Comment by bruquevedo** [comment]
I received the reminder in slack, the way you are doing this time is really good. 
In the issue description you said "We need to have reminders of the tasks due today and tomorrow on Slack (done), and meetings scheduled on Calendar - I didn't receive the invite in google calendar.

**Comment by vjpixel** [comment]
Oh, I forgot this part. Thank you for the reminder.

**Comment by vjpixel** [comment]
I just proposed on Slack to cancel the two meetings I'm part, and that the members of the other meetings schedule them on Calendar (so I don't need to have a meeting in my Calendar that I won't attend).

**Comment by vjpixel** [comment]
Considering this, can you please review @bruquevedo?

**Comment by bruquevedo** [comment]
Considering this, you did all.
