### ISSUE TITLE
As a staff member, I need established goals, so I can make better decisions.

### ISSUE THREAD

**Issue by vjpixel** [memeLab/bucoli.co#91]
We discussed our goals in a generic way, but we need to be more specific, so we know when we reached the goals.

I'm using the OKR framework to set the goals in a specific way. To understand what OKR is, I recommend [this TED talk](https://youtu.be/L4N1q4RNi9I) and the [OKR Wikipedia page](https://en.wikipedia.org/wiki/OKR). 

We need to have measurable goals.

**Comment by vjpixel** [comment]
OKR has two components, the Objective and the Key Results:

**Objectives** are memorable qualitative descriptions of what you want to achieve. Objectives should be short, inspirational and engaging. An Objective should motivate and challenge the team.

**Key Results** are a set of metrics that measure your progress towards the Objective. For each Objective, you should have a set of 2 to 5 Key Results. More than that and no one will remember them. All Key Results have to be quantitative and measurable.

Source: https://felipecastro.com/en/okr/what-is-okr/

**Comment by vjpixel** [comment]
My proposal for May:

**Objective**
Increase our community

**Key results**
. Get 72 new subscribers.
. Have a day with more than 50 users (based on Google Analytics).
. Have comments from 10 community members in the Feedback.

Can you review @bruquevedo ?

**Comment by bruquevedo** [comment]
> 
> 
> My proposal for May:
> 
> **Objective**
> Increase our community
> 
> **Key results**
> . Get 72 new subscribers.
> . Have a day with more than 50 users (based on Google Analytics).
> . Have comments from 10 community members in the Feedback.
> 
> Can you review @bruquevedo ? (confirming that you find these numbers challenging and at the same time achievable).

Yes, I think that we have challenging numbers but we can work to achive than. Once we start to publicize bucoli.co its going to help increase our community
